services:
  file-server:
    image: nginx:alpine
    container_name: csv-file-server
    ports:
      - "8080:80"
    volumes:
      - ./reports:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - grafana-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-load-testing
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=marcusolsson-csv-datasource
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./reports:/var/lib/grafana/csv-data:ro
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    restart: unless-stopped
    networks:
      - grafana-network

volumes:
  grafana-storage:

networks:
  grafana-network:
    driver: bridge