services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-load-testing
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped
    networks:
      - grafana-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-load-testing
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    restart: unless-stopped
    networks:
      - grafana-network

volumes:
  grafana-storage:

networks:
  grafana-network:
    driver: bridge